// <auto-generated />
namespace TS.Web.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class a14 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(a14));
        
        string IMigrationMetadata.Id
        {
            get { return "201709100951245_a14"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
