// <auto-generated />
namespace TS.Web.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class a17 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(a17));
        
        string IMigrationMetadata.Id
        {
            get { return "201709101346047_a17"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
